In [1]:
import pandas as pd
import csv

In [2]:
#url for 2023
url2023 = "https://aa.usno.navy.mil/calculated/durdaydark?year=2023&task=1&lat=38.89&lon=-77.03&label=Washington%2C+DC&tz=5&tz_sign=-1&submit=Get+Data"
data2023 = pd.read_html(url2023,header=1)[0]  # Assuming the table is the first one on the page
# Create a DataFrame (example)
data2023 = pd.DataFrame(data2023)

ValueError: Passed header=1 but only 1 lines in file

In [ ]:
data2023 ['NMJan'] = '01'
Jan = ['NMJan', 'Jan.']


# Select the columns for January and rearrange them

Jan2023 = data2023[Jan]
Jan2023 = Jan2023.reindex(columns=Jan)
Jan2023 = Jan2023.dropna()


# Split the time into hours and minutes
Jan2023['Time_Hour'] = Jan2023['Jan.'].str.split(':').str[0].astype(int)
Jan2023['Time_Minute'] = Jan2023['Jan.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Jan2023['Time_Total_Minutes'] = Jan2023['Time_Hour'] * 60 + Jan2023['Time_Minute']

# Drop the intermediate columns if needed
Jan2023 = Jan2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Jan2023.rename(columns={'Jan.': 'Hours of Darktime'}, inplace=True)
Jan2023.rename(columns={'NMJan': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_jan = Jan2023['Time_Total_Minutes'].sum()
Jan2023 = pd.DataFrame({'Month': ['01'], 'Total_Time_Minutes': [total_time_minutes_jan]})

data2023 ['NMFeb'] = '02'
Feb = ['NMFeb', 'Feb.']


# Select the columns for Febuary and rearrange them

Feb2023 = data2023[Feb]
Feb2023 = Feb2023.reindex(columns=Feb)
Feb2023 = Feb2023.dropna()


# Split the time into hours and minutes
Feb2023['Time_Hour'] = Feb2023['Feb.'].str.split(':').str[0].astype(int)
Feb2023['Time_Minute'] = Feb2023['Feb.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Feb2023['Time_Total_Minutes'] = Feb2023['Time_Hour'] * 60 + Feb2023['Time_Minute']

# Drop the intermediate columns if needed
Feb2023 = Feb2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Feb2023.rename(columns={'Feb.': 'Hours of Darktime'}, inplace=True)
Feb2023.rename(columns={'NMFeb': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Feb = Feb2023['Time_Total_Minutes'].sum()
Feb2023 = pd.DataFrame({'Month': ['02'], 'Total_Time_Minutes': [total_time_minutes_Feb]})

data2023 ['NMMar'] = '03'
Mar = ['NMMar', 'Mar.']


# Select the columns for Maruary and rearrange them

Mar2023 = data2023[Mar]
Mar2023 = Mar2023.reindex(columns=Mar)
Mar2023 = Mar2023.dropna()


# Split the time into hours and minutes
Mar2023['Time_Hour'] = Mar2023['Mar.'].str.split(':').str[0].astype(int)
Mar2023['Time_Minute'] = Mar2023['Mar.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Mar2023['Time_Total_Minutes'] = Mar2023['Time_Hour'] * 60 + Mar2023['Time_Minute']

# Drop the intermediate columns if needed
Mar2023 = Mar2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Mar2023.rename(columns={'Mar.': 'Hours of Darktime'}, inplace=True)
Mar2023.rename(columns={'NMMar': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Mar = Mar2023['Time_Total_Minutes'].sum()
Mar2023 = pd.DataFrame({'Month': ['03'], 'Total_Time_Minutes': [total_time_minutes_Mar]})

data2023 ['NMApr'] = '04'
Apr = ['NMApr', 'Apr.']


# Select the columns for Apruary and rearrange them

Apr2023 = data2023[Apr]
Apr2023 = Apr2023.reindex(columns=Apr)
Apr2023 = Apr2023.dropna()


# Split the time into hours and minutes
Apr2023['Time_Hour'] = Apr2023['Apr.'].str.split(':').str[0].astype(int)
Apr2023['Time_Minute'] = Apr2023['Apr.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Apr2023['Time_Total_Minutes'] = Apr2023['Time_Hour'] * 60 + Apr2023['Time_Minute']

# Drop the intermediate columns if needed
Apr2023 = Apr2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Apr2023.rename(columns={'Apr.': 'Hours of Darktime'}, inplace=True)
Apr2023.rename(columns={'NMApr': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Apr = Apr2023['Time_Total_Minutes'].sum()
Apr2023 = pd.DataFrame({'Month': ['04'], 'Total_Time_Minutes': [total_time_minutes_Apr]})

data2023 ['NMMay'] = '05'
May = ['NMMay', 'May']


# Select the columns for Mayuary and rearrange them

May2023 = data2023[May]
May2023 = May2023.reindex(columns=May)
May2023 = May2023.dropna()


# Split the time into hours and minutes
May2023['Time_Hour'] = May2023['May'].str.split(':').str[0].astype(int)
May2023['Time_Minute'] = May2023['May'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
May2023['Time_Total_Minutes'] = May2023['Time_Hour'] * 60 + May2023['Time_Minute']

# Drop the intermediate columns if needed
May2023 = May2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
May2023.rename(columns={'May': 'Hours of Darktime'}, inplace=True)
May2023.rename(columns={'NMMay': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_May = May2023['Time_Total_Minutes'].sum()
May2023 = pd.DataFrame({'Month': ['05'], 'Total_Time_Minutes': [total_time_minutes_May]})


data2023 ['NMJune'] = '06'
June = ['NMJune', 'June']


# Select the columns for Juneuary and rearrange them

June2023 = data2023[June]
June2023 = June2023.reindex(columns=June)
June2023 = June2023.dropna()


# Split the time into hours and minutes
June2023['Time_Hour'] = June2023['June'].str.split(':').str[0].astype(int)
June2023['Time_Minute'] = June2023['June'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
June2023['Time_Total_Minutes'] = June2023['Time_Hour'] * 60 + June2023['Time_Minute']

# Drop the intermediate columns if needed
June2023 = June2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
June2023.rename(columns={'June': 'Hours of Darktime'}, inplace=True)
June2023.rename(columns={'NMJune': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_June = June2023['Time_Total_Minutes'].sum()
June2023 = pd.DataFrame({'Month': ['06'], 'Total_Time_Minutes': [total_time_minutes_June]})

data2023 ['NMJuly'] = '07'
July = ['NMJuly', 'July']


# Select the columns for Julyuary and rearrange them

July2023 = data2023[July]
July2023 = July2023.reindex(columns=July)
July2023 = July2023.dropna()


# Split the time into hours and minutes
July2023['Time_Hour'] = July2023['July'].str.split(':').str[0].astype(int)
July2023['Time_Minute'] = July2023['July'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
July2023['Time_Total_Minutes'] = July2023['Time_Hour'] * 60 + July2023['Time_Minute']

# Drop the intermediate columns if needed
July2023 = July2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
July2023.rename(columns={'July': 'Hours of Darktime'}, inplace=True)
July2023.rename(columns={'NMJuly': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_July = July2023['Time_Total_Minutes'].sum()
July2023 = pd.DataFrame({'Month': ['07'], 'Total_Time_Minutes': [total_time_minutes_July]})

data2023 ['NMAug'] = '08'
Aug = ['NMAug', 'Aug.']


# Select the columns for Auguary and rearrange them

Aug2023 = data2023[Aug]
Aug2023 = Aug2023.reindex(columns=Aug)
Aug2023 = Aug2023.dropna()


# Split the time into hours and minutes
Aug2023['Time_Hour'] = Aug2023['Aug.'].str.split(':').str[0].astype(int)
Aug2023['Time_Minute'] = Aug2023['Aug.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Aug2023['Time_Total_Minutes'] = Aug2023['Time_Hour'] * 60 + Aug2023['Time_Minute']

# Drop the intermediate columns if needed
Aug2023 = Aug2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Aug2023.rename(columns={'Aug.': 'Hours of Darktime'}, inplace=True)
Aug2023.rename(columns={'NMAug': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Aug = Aug2023['Time_Total_Minutes'].sum()
Aug2023 = pd.DataFrame({'Month': ['08'], 'Total_Time_Minutes': [total_time_minutes_Aug]})


data2023 ['NMSep'] = '09'
Sep = ['NMSep', 'Sep.']

# Select the columns for Sepuary and rearrange them

Sep2023 = data2023[Sep]
Sep2023 = Sep2023.reindex(columns=Sep)
Sep2023 = Sep2023.dropna()


# Split the time into hours and minutes
Sep2023['Time_Hour'] = Sep2023['Sep.'].str.split(':').str[0].astype(int)
Sep2023['Time_Minute'] = Sep2023['Sep.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Sep2023['Time_Total_Minutes'] = Sep2023['Time_Hour'] * 60 + Sep2023['Time_Minute']

# Drop the intermediate columns if needed
Sep2023 = Sep2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Sep2023.rename(columns={'Sep.': 'Hours of Darktime'}, inplace=True)
Sep2023.rename(columns={'NMSep': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Sep = Sep2023['Time_Total_Minutes'].sum()
Sep2023 = pd.DataFrame({'Month': ['09'], 'Total_Time_Minutes': [total_time_minutes_Sep]})

data2023 ['NMOct'] = '10'
Oct = ['NMOct', 'Oct.']


# Select the columns for Octuary and rearrange them

Oct2023 = data2023[Oct]
Oct2023 = Oct2023.reindex(columns=Oct)
Oct2023 = Oct2023.dropna()


# Split the time into hours and minutes
Oct2023['Time_Hour'] = Oct2023['Oct.'].str.split(':').str[0].astype(int)
Oct2023['Time_Minute'] = Oct2023['Oct.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Oct2023['Time_Total_Minutes'] = Oct2023['Time_Hour'] * 60 + Oct2023['Time_Minute']

# Drop the intermediate columns if needed
Oct2023 = Oct2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Oct2023.rename(columns={'Oct.': 'Hours of Darktime'}, inplace=True)
Oct2023.rename(columns={'NMOct': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Oct = Oct2023['Time_Total_Minutes'].sum()
Oct2023 = pd.DataFrame({'Month': ['10'], 'Total_Time_Minutes': [total_time_minutes_Oct]})

data2023 ['NMNov'] = '11'
Nov = ['NMNov', 'Nov.']


# Select the columns for Novuary and rearrange them

Nov2023 = data2023[Nov]
Nov2023 = Nov2023.reindex(columns=Nov)
Nov2023 = Nov2023.dropna()


# Split the time into hours and minutes
Nov2023['Time_Hour'] = Nov2023['Nov.'].str.split(':').str[0].astype(int)
Nov2023['Time_Minute'] = Nov2023['Nov.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Nov2023['Time_Total_Minutes'] = Nov2023['Time_Hour'] * 60 + Nov2023['Time_Minute']

# Drop the intermediate columns if needed
Nov2023 = Nov2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Nov2023.rename(columns={'Nov.': 'Hours of Darktime'}, inplace=True)
Nov2023.rename(columns={'NMNov': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Nov = Nov2023['Time_Total_Minutes'].sum()
Nov2023 = pd.DataFrame({'Month': ['11'], 'Total_Time_Minutes': [total_time_minutes_Nov]})

data2023 ['NMDec'] = '12'
Dec = ['NMDec', 'Dec.']


# Select the columns for Decuary and rearrange them

Dec2023 = data2023[Dec]
Dec2023 = Dec2023.reindex(columns=Dec)
Dec2023 = Dec2023.dropna()


# Split the time into hours and minutes
Dec2023['Time_Hour'] = Dec2023['Dec.'].str.split(':').str[0].astype(int)
Dec2023['Time_Minute'] = Dec2023['Dec.'].str.split(':').str[1].astype(int)

# Convert the time to total minutes
Dec2023['Time_Total_Minutes'] = Dec2023['Time_Hour'] * 60 + Dec2023['Time_Minute']

# Drop the intermediate columns if needed
Dec2023 = Dec2023.drop(columns=['Time_Hour', 'Time_Minute'])

#re-name month column
Dec2023.rename(columns={'Dec.': 'Hours of Darktime'}, inplace=True)
Dec2023.rename(columns={'NMDec': 'Month'}, inplace=True)

#Sum Time_Total_minutes 
total_time_minutes_Dec = Dec2023['Time_Total_Minutes'].sum()
Dec2023 = pd.DataFrame({'Month': ['12'], 'Total_Time_Minutes': [total_time_minutes_Dec]})




#combine Dataframes 

LightDatabymonth2023 = pd.concat([Jan2023,Feb2023,Mar2023,Apr2023,May2023,June2023,July2023,Aug2023,Sep2023,Oct2023,Nov2023,Dec2023], axis=0)
LightDatabymonth2023

  Month  Total_Time_Minutes
0    01               26407
0    02               22255
0    03               22388
0    04               19386
0    05               18041
0    06               16476
0    07               17525
0    08               19265
0    09               20821
0    10               23856
0    11               25069
0    12               26974

In [ ]:
#Save Dataframe as CSV
LightDatabymonth2023.to_csv("LightDatabymonth2023.csv", index=False)