In [1]:
import pandas as pd
import csv

In [15]:
#url for 2023
url2023 = "https://aa.usno.navy.mil/calculated/durdaydark?year=2023&task=1&lat=38.89&lon=-77.03&label=Washington%2C+DC&tz=5&tz_sign=-1&submit=Get+Data"
data2023 = pd.read_html(url2023,header=1)[0]  # Assuming the table is the first one on the page

In [25]:
# Create a DataFrame (example)
data2023 = pd.DataFrame(data2023)

# Add a new column 'Year' with the constant value '2023'
data2023 ['Year'] = 2023

# Display the updated DataFrame
data2023 

#re-arrage columns 
desired_columns = ['Day','Year','Jan.','Feb.', 'Mar.', 'Apr.', 'May', 'June', 'July', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'] 
data2023 = data2023[desired_columns]

data2023 = data2023.reindex(columns=desired_columns)
data2023

,Day,Year,Jan.,Feb.,Mar.,Apr.,May,June,July,Aug.,Sep.,Oct.,Nov.,Dec.
0,1,2023,14:30,13:45,12:40,11:22,10:10,09:17,09:09,09:50,10:58,12:13,13:27,14:21
1,2,2023,14:29,13:43,12:38,11:19,10:08,09:16,09:10,09:52,11:01,12:15,13:29,14:22
2,3,2023,14:28,13:41,12:35,11:17,10:06,09:15,09:10,09:53,11:03,12:18,13:32,14:23
3,4,2023,14:28,13:39,12:33,11:14,10:04,09:14,09:11,09:55,11:05,12:20,13:34,14:24
4,5,2023,14:27,13:37,12:30,11:12,10:02,09:13,09:12,09:57,11:08,12:23,13:36,14:25
5,6,2023,14:26,13:35,12:28,11:09,10:00,09:13,09:13,09:59,11:10,12:25,13:38,14:26
6,7,2023,14:25,13:32,12:25,11:07,09:58,09:12,09:14,10:01,11:13,12:28,13:40,14:27
7,8,2023,14:24,13:30,12:23,11:04,09:56,09:11,09:14,10:04,11:15,12:30,13:42,14:28
8,9,2023,14:23,13:28,12:20,11:02,09:54,09:10,09:15,10:06,11:18,12:33,13:44,14:29
9,10,2023,14:22,13:26,12:17,10:59,09:52,09:10,09:16,10:08,11:20,12:35,13:46,14:29
10,11,2023,14:20,13:23,12:15,10:57,09:50,09:09,09:18,10:10,11:23,12:38,13:48,14:30
11,12,2023,14:19,13:21,12:12,10:54,09:48,09:09,09:19,10:12,11:25,12:40,13:50,14:31
12,13,2023,14:18,13:19,12:10,10:52,09:46,09:08,09:20,10:14,11:28,12:43,13:52,14:31
13,14,2023,14:16,13:16,12:07,10:49,09:44,09:08,09:21,10:16,11:30,12:45,13:54,14:32
14,15,2023,14:15,13:14,12:05,10:47,09:42,09:07,09:22,10:19,11:33,12:47,13:56,14:32
15,16,2023,14:14,13:12,12:02,10:45,09:40,09:07,09:24,10:21,11:35,12:50,13:58,14:33
16,17,2023,14:12,13:09,12:00,10:42,09:39,09:07,09:25,10:23,11:38,12:52,14:00,14:33
17,18,2023,14:11,13:07,11:57,10:40,09:37,09:07,09:26,10:25,11:40,12:55,14:01,14:33
18,19,2023,14:09,13:05,11:55,10:37,09:35,09:06,09:28,10:28,11:43,12:57,14:03,14:33
19,20,2023,14:07,13:02,11:52,10:35,09:34,09:06,09:29,10:30,11:45,12:59,14:05,14:33
20,21,2023,14:06,13:00,11:49,10:33,09:32,09:06,09:31,10:32,11:48,13:02,14:07,14:34
21,22,2023,14:04,12:57,11:47,10:30,09:31,09:06,09:32,10:34,11:50,13:04,14:08,14:34
22,23,2023,14:02,12:55,11:44,10:28,09:29,09:06,09:34,10:37,11:53,13:07,14:10,14:33
23,24,2023,14:01,12:53,11:42,10:26,09:28,09:07,09:35,10:39,11:55,13:09,14:11,14:33
24,25,2023,13:59,12:50,11:39,10:23,09:26,09:07,09:37,10:41,11:58,13:11,14:13,14:33
25,26,2023,13:57,12:48,11:37,10:21,09:25,09:07,09:39,10:44,12:00,13:14,14:14,14:33
26,27,2023,13:55,12:45,11:34,10:19,09:23,09:07,09:41,10:46,12:03,13:16,14:16,14:33
27,28,2023,13:53,12:43,11:32,10:17,09:22,09:08,09:42,10:49,12:05,13:18,14:17,14:32
28,29,2023,13:51,NaN,11:29,10:14,09:21,09:08,09:44,10:51,12:08,13:21,14:18,14:32
29,30,2023,13:49,NaN,11:27,10:12,09:20,09:09,09:46,10:53,12:10,13:23,14:20,14:31
30,31,2023,13:47,NaN,11:24,NaN,09:19,NaN,09:48,10:56,NaN,13:25,NaN,14:31

In [23]:
# Define the columns you want to keep as identifiers
id_vars = ['Day']

# Melt the DataFrame to convert columns into rows
data2023_melted = data2023.melt(id_vars=id_vars, var_name='Month', value_name='Daylight_Hours')

# Reorder the columns if needed
data2023_melted = data2023_melted[['Day', 'Month', 'Daylight_Hours']]

# Display the melted DataFrame
print(data2023_melted)

     Day Month Daylight_Hours
0      1  Year           2023
1      2  Year           2023
2      3  Year           2023
3      4  Year           2023
4      5  Year           2023
..   ...   ...            ...
398   27  Dec.          14:33
399   28  Dec.          14:32
400   29  Dec.          14:32
401   30  Dec.          14:31
402   31  Dec.          14:31

[403 rows x 3 columns]

In [ ]:
# Create a new column combining the day with a fixed month and year
data2023['Full_date'] = '1/' + data2023['Day'].astype(str) + '/2023'

# Convert the "full_date" column to a datetime format
data2023['Full_date'] = pd.to_datetime(data2023['Full_date'], format='%m/%d/%Y')

data2023['Full_date'] = data2023['Full_date'].dt.strftime('%d/%m/%Y')

# Drop the original "day" column if needed
data2023 = data2023.drop(columns=['Day'])

,Full_date,Jan.,Feb.,Mar.,Apr.,May,June,July,Aug.,Sep.,Oct.,Nov.,Dec.
0,01/01/2023,14:30,13:45,12:40,11:22,10:10,09:17,09:09,09:50,10:58,12:13,13:27,14:21
1,02/01/2023,14:29,13:43,12:38,11:19,10:08,09:16,09:10,09:52,11:01,12:15,13:29,14:22
2,03/01/2023,14:28,13:41,12:35,11:17,10:06,09:15,09:10,09:53,11:03,12:18,13:32,14:23
3,04/01/2023,14:28,13:39,12:33,11:14,10:04,09:14,09:11,09:55,11:05,12:20,13:34,14:24
4,05/01/2023,14:27,13:37,12:30,11:12,10:02,09:13,09:12,09:57,11:08,12:23,13:36,14:25
5,06/01/2023,14:26,13:35,12:28,11:09,10:00,09:13,09:13,09:59,11:10,12:25,13:38,14:26
6,07/01/2023,14:25,13:32,12:25,11:07,09:58,09:12,09:14,10:01,11:13,12:28,13:40,14:27
7,08/01/2023,14:24,13:30,12:23,11:04,09:56,09:11,09:14,10:04,11:15,12:30,13:42,14:28
8,09/01/2023,14:23,13:28,12:20,11:02,09:54,09:10,09:15,10:06,11:18,12:33,13:44,14:29
9,10/01/2023,14:22,13:26,12:17,10:59,09:52,09:10,09:16,10:08,11:20,12:35,13:46,14:29
10,11/01/2023,14:20,13:23,12:15,10:57,09:50,09:09,09:18,10:10,11:23,12:38,13:48,14:30
11,12/01/2023,14:19,13:21,12:12,10:54,09:48,09:09,09:19,10:12,11:25,12:40,13:50,14:31
12,13/01/2023,14:18,13:19,12:10,10:52,09:46,09:08,09:20,10:14,11:28,12:43,13:52,14:31
13,14/01/2023,14:16,13:16,12:07,10:49,09:44,09:08,09:21,10:16,11:30,12:45,13:54,14:32
14,15/01/2023,14:15,13:14,12:05,10:47,09:42,09:07,09:22,10:19,11:33,12:47,13:56,14:32
15,16/01/2023,14:14,13:12,12:02,10:45,09:40,09:07,09:24,10:21,11:35,12:50,13:58,14:33
16,17/01/2023,14:12,13:09,12:00,10:42,09:39,09:07,09:25,10:23,11:38,12:52,14:00,14:33
17,18/01/2023,14:11,13:07,11:57,10:40,09:37,09:07,09:26,10:25,11:40,12:55,14:01,14:33
18,19/01/2023,14:09,13:05,11:55,10:37,09:35,09:06,09:28,10:28,11:43,12:57,14:03,14:33
19,20/01/2023,14:07,13:02,11:52,10:35,09:34,09:06,09:29,10:30,11:45,12:59,14:05,14:33
20,21/01/2023,14:06,13:00,11:49,10:33,09:32,09:06,09:31,10:32,11:48,13:02,14:07,14:34
21,22/01/2023,14:04,12:57,11:47,10:30,09:31,09:06,09:32,10:34,11:50,13:04,14:08,14:34
22,23/01/2023,14:02,12:55,11:44,10:28,09:29,09:06,09:34,10:37,11:53,13:07,14:10,14:33
23,24/01/2023,14:01,12:53,11:42,10:26,09:28,09:07,09:35,10:39,11:55,13:09,14:11,14:33
24,25/01/2023,13:59,12:50,11:39,10:23,09:26,09:07,09:37,10:41,11:58,13:11,14:13,14:33
25,26/01/2023,13:57,12:48,11:37,10:21,09:25,09:07,09:39,10:44,12:00,13:14,14:14,14:33
26,27/01/2023,13:55,12:45,11:34,10:19,09:23,09:07,09:41,10:46,12:03,13:16,14:16,14:33
27,28/01/2023,13:53,12:43,11:32,10:17,09:22,09:08,09:42,10:49,12:05,13:18,14:17,14:32
28,29/01/2023,13:51,NaN,11:29,10:14,09:21,09:08,09:44,10:51,12:08,13:21,14:18,14:32
29,30/01/2023,13:49,NaN,11:27,10:12,09:20,09:09,09:46,10:53,12:10,13:23,14:20,14:31
30,31/01/2023,13:47,NaN,11:24,NaN,09:19,NaN,09:48,10:56,NaN,13:25,NaN,14:31

In [ ]:
#url for 2022
url2022 = "https://aa.usno.navy.mil/calculated/durdaydark?year=2022&task=1&lat=38.89&lon=-77.03&label=Washington%2C+DC&tz=5&tz_sign=-1&submit=Get+Data"
data2022 = pd.read_html(url2022,header=1)[0]  # Assuming the table is the first one on the page

# Create a new column combining the day with a fixed month and year
data2022['Full_date'] = '1/' + data2022['Day'].astype(str) + '/2022'

# Convert the "full_date" column to a datetime format
data2022['Full_date'] = pd.to_datetime(data2022['Full_date'], format='%m/%d/%Y')

data2022['Full_date'] = data2022['Full_date'].dt.strftime('%d/%m/%Y')

# Drop the original "day" column if needed
data2022 = data2022.drop(columns=['Day'])

#re-arrage columns 
desired_columns = ['Full_date', 'Jan.', 'Feb.', 'Mar.', 'Apr.', 'May.', 'June.', 'July.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'] 
data2022 = data2022[desired_columns]

data2022

In [ ]:
#url for 2021
url2021 = "https://aa.usno.navy.mil/calculated/durdaydark?year=2021&task=1&lat=38.89&lon=-77.03&label=Washington%2C+DC&tz=5&tz_sign=-1&submit=Get+Data"
data2021 = pd.read_html(url2021,header=1)[0]  # Assuming the table is the first one on the page

# Create a new column combining the day with a fixed month and year
data2021['Full_date'] = '1/' + data2021['Day'].astype(str) + '/2021'

# Convert the "full_date" column to a datetime format
data2021['Full_date'] = pd.to_datetime(data2021['Full_date'], format='%m/%d/%Y')

data2021['Full_date'] = data2021['Full_date'].dt.strftime('%d/%m/%Y')

# Drop the original "day" column if needed
data2021 = data2021.drop(columns=['Day'])

#re-arrage columns 
desired_columns = ['Full_date', 'Jan.', 'Feb.', 'Mar.', 'Apr.', 'May.', 'June.', 'July.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'] 
data2021 = data2021[desired_columns]

data2021

In [ ]:
#url for 2020
url2020 = "https://aa.usno.navy.mil/calculated/durdaydark?year=2020&task=1&lat=38.89&lon=-77.03&label=Washington%2C+DC&tz=5&tz_sign=-1&submit=Get+Data"
data2020 = pd.read_html(url2020,header=1)[0]  # Assuming the table is the first one on the page

# Create a new column combining the day with a fixed month and year
data2020['Full_date'] = '1/' + data2020['Day'].astype(str) + '/2020'

# Convert the "full_date" column to a datetime format
data2020['Full_date'] = pd.to_datetime(data2020['Full_date'], format='%m/%d/%Y')

data2020['Full_date'] = data2020['Full_date'].dt.strftime('%d/%m/%Y')

# Drop the original "day" column if needed
data2020 = data2020.drop(columns=['Day'])

#re-arrage columns 
desired_columns = ['Full_date', 'Jan.', 'Feb.', 'Mar.', 'Apr.', 'May.', 'June.', 'July.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'] 
data2020 = data2020[desired_columns]

data2020

In [ ]:
#url for 2019
url2019 = "https://aa.usno.navy.mil/calculated/durdaydark?year=2019&task=1&lat=38.89&lon=-77.03&label=Washington%2C+DC&tz=5&tz_sign=-1&submit=Get+Data"
data2019 = pd.read_html(url2019,header=1)[0]  # Assuming the table is the first one on the page

# Create a new column combining the day with a fixed month and year
data2019['Full_date'] = '1/' + data2019['Day'].astype(str) + '/2019'

# Convert the "full_date" column to a datetime format
data2019['Full_date'] = pd.to_datetime(data2019['Full_date'], format='%m/%d/%Y')

data2019['Full_date'] = data2019['Full_date'].dt.strftime('%d/%m/%Y')

# Drop the original "day" column if needed
data2019 = data2019.drop(columns=['Day'])

#re-arrage columns 
desired_columns = ['Full_date', 'Jan.', 'Feb.', 'Mar.', 'Apr.', 'May.', 'June.', 'July.', 'Aug.', 'Sep.', 'Oct.', 'Nov.', 'Dec.'] 
data2019 = data2019[desired_columns]


data2019

In [ ]:
data2019

In [ ]:
#save data to csv file 
folder_path = "light data"
data2019.to_csv(folder_path + "lightdata2019.csv", index=False)
data2020.to_csv(folder_path + "lightdata2020.csv", index=False)
data2021.to_csv(folder_path + "lightdata2021.csv", index=False)
data2022.to_csv(folder_path + "lightdata2022.csv", index=False)
data2023.to_csv(folder_path + "lightdata2023.csv", index=False)